name: CI

on: [push]

jobs:
  
  test-linux-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@master
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
      - name: Run unit tests
        run: Rscript -e 'install.packages(c("devtools", "testthat", "LaplacesDemon", "VGAM", "evd", "hoa", "skellam", "triangle", "actuar")); devtools::test()'
  
  test-windws:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        run: Rscript.exe -e 'install.packages(c("devtools", "testthat", "LaplacesDemon", "VGAM", "evd", "hoa", "skellam", "triangle", "actuar")); devtools::test()'
