name: CI

on: [push]

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@v1
      - run: Rscript -e 'install.packages(c("devtools", "testthat", "LaplacesDemon", "VGAM", "evd", "hoa", "skellam", "triangle", "actuar"))'
      - run: Rscript -e 'devtools::test()'
